version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./webapp:/opt/webapp
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=backland
      - DB_PASSWORD=backland
      - DB_DATABASE=backland

  db:
    hostname: db
    image: postgres:latest
    ports:
      - "5432:5432"
